(()=>{if(!document.querySelector('link[data-ui-system]')){const l=document.createElement('link');l.rel='stylesheet';l.href='ui-system.css';l.dataset.uiSystem='1';document.head.append(l)}if(!document.querySelector('script[data-ui-dialog]')){const s=document.createElement('script');s.src='ui-dialog.js';s.dataset.uiDialog='1';document.head.append(s)}})();
const API='https://rzhjgjujmvxhvkbuofck.supabase.co',KEY='sb_publishable_j3VXPJJw6znG_hquWCRIfg_1nnCDp9F',SESSION='eutteum50:portal-session';
async function rpc(name,body={}){const r=await fetch(`${API}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||'서버 오류');return d}
function scalar(v){if(Array.isArray(v)&&v.length===1)return scalar(v[0]);if(v&&typeof v==='object'){const k=Object.keys(v);if(k.length===1)return v[k[0]]}return v}
function session(){try{return JSON.parse(localStorage.getItem(SESSION)||'null')}catch{return null}}
function storeName(){const s=session();return s?.store?.name||s?.store?.full_name||'지점명'}
function aiUsage(){const s=session()?.store||{};const used=Number(s.ai_used??s.ai_usage??s.used_ai??0)||0;const limit=Number(s.ai_limit??s.ai_quota??s.total_ai??20)||20;return{used,limit}}
async function refreshAiUsage(){const ses=session();if(!ses?.token)return aiUsage();try{const r=await fetch(`${API}/functions/v1/generate-content`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify({action:'status',storeToken:ses.token,token:ses.token})});const d=await r.json();if(!r.ok||!d?.usage)throw new Error(d?.message||'사용량 조회 실패');const u=d.usage,store={...(ses.store||{}),ai_used:Number(u.used||0),ai_limit:Number(u.limit||20),ai_remaining:Number(u.remaining??Math.max(0,Number(u.limit||20)-Number(u.used||0))),ai_reset_date:u.next_reset_date||null};localStorage.setItem(SESSION,JSON.stringify({...ses,store}));return{used:store.ai_used,limit:store.ai_limit,remaining:store.ai_remaining,next_reset_date:store.ai_reset_date}}catch(e){console.warn(e);return aiUsage()}}
function go(u){location.href=u}
document.addEventListener('DOMContentLoaded',()=>{const stage=document.querySelector('.art-stage');if(stage&&!stage.querySelector('.logo-home-hit')){const b=document.createElement('button');b.type='button';b.className='logo-home-hit';b.setAttribute('aria-label','서비스 선택 홈');b.onclick=()=>go('service.html');stage.append(b)}});
