(()=>{
const ses=session();if(!ses?.token){location.replace('index.html');return}
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selectedId='',pinValue='',part='glasses',avatar={preset:'default',glasses:'default',outfit:'none',accessories:[]};
const files={glasses:'glasses',outfit:'outfit',accessory:'accessory'},prefixPart={glasses:'g',outfit:'o',accessory:'a'},labels={glasses:['호피 안경','그린 안경','하트 안경','검정 안경','선글라스','오렌지 안경'],outfit:['세일러복','멜빵옷','가운','정장','유니폼','후드티'],accessory:['머리핀','넥타이','머리띠','목도리','왕관','튜브']};
const itemScroller=$('itemOptions');
function norm(a={}){return normalizeQuizAvatar(a)}
function avatarLayers(a={}){return `<span class="quiz-avatar-fit">${quizAvatarLayers(a)}</span>`}
function avatarThumb(a={}){return `<span class="quiz-avatar-fit thumb">${quizAvatarLayers(a)}</span>`}
async function choose(id,pin=''){const d=scalar(await rpc('quiz_load_progress',{p_token:ses.token,p_profile_id:id,p_pin:pin}));sessionStorage.setItem('eutteum50:quiz-active-profile',JSON.stringify({id,display_name:d.display_name,xp:Number(d.xp||0),avatar:d.avatar||{},pin}));location.href='quiz.html'}
async function load(){try{const raw=await rpc('quiz_list_profiles',{p_token:ses.token}),list=Array.isArray(raw)?raw:scalar(raw)||[];$('profiles').innerHTML=list.map(p=>`<button class="profile-card" data-id="${esc(p.id)}" data-pin="${p.has_pin?'1':'0'}"><span class="profile-face">${avatarThumb(p.avatar)}</span><span class="profile-copy"><strong>${esc(p.display_name)}</strong><small>${Number(p.xp||0).toLocaleString()} XP${p.has_pin?' · PIN 사용':''}</small></span><b class="chev">›</b></button>`).join('')||'<p class="empty">아직 프로필이 없습니다. 새 프로필을 만들어 주세요.</p>';$('profiles').querySelectorAll('button').forEach(b=>b.onclick=async()=>{selectedId=b.dataset.id;if(b.dataset.pin==='1'){openPin();return}b.disabled=true;try{await choose(selectedId)}catch(e){$('profileError').textContent=e.message;b.disabled=false}})}catch(e){$('profiles').innerHTML=`<p class="empty">프로필을 불러오지 못했습니다.<br>${esc(e.message)}</p>`}}
function draw(){avatar=norm(avatar);$('avatarStage').className='avatar-stage';$('avatarStage').innerHTML=avatarLayers(avatar);document.querySelectorAll('#customTabs button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.part===part)));const items=[];if(part==='glasses'){items.push(`<button type="button" data-value="default" aria-pressed="${avatar.glasses==='default'}"><img src="avatar/base-default.png" alt="기본 빨간 안경"></button>`);items.push(`<button type="button" class="none" data-value="none" aria-pressed="${avatar.glasses==='none'}">선택 안함</button>`);}else if(part==='outfit'){items.push(`<button type="button" class="none" data-value="none" aria-pressed="${avatar.outfit==='none'}">선택 안함</button>`);}else{items.push(`<button type="button" class="none" data-value="clear" aria-pressed="${avatar.accessories.length===0}">선택 안함</button>`);}for(let i=1;i<=6;i++){const value=prefixPart[part]+i;const pressed=part==='accessory'?avatar.accessories.includes(value):avatar[part]===value;items.push(`<button type="button" data-value="${value}" aria-pressed="${pressed}"><img src="avatar/fit/${files[part]}-${i}.png" alt="${labels[part][i-1]}"></button>`)}$('itemOptions').innerHTML=items.join('');toggleArrowState()}
function scrollItems(dir){const card=$('itemOptions').querySelector('button');const step=(card?.offsetWidth||96)+7;$('itemOptions').scrollBy({left:dir*step,behavior:'smooth'});setTimeout(toggleArrowState,240)}
function toggleArrowState(){const box=$('itemOptions');if(!box)return;$('itemsPrev').disabled=box.scrollLeft<=4;$('itemsNext').disabled=box.scrollLeft+box.clientWidth>=box.scrollWidth-4}
$('itemsPrev').onclick=()=>scrollItems(-1);$('itemsNext').onclick=()=>scrollItems(1);itemScroller.addEventListener('scroll',toggleArrowState);
$('openCreate').onclick=()=>{avatar={preset:'default',glasses:'default',outfit:'none',accessories:[]};$('profileApp').classList.add('creating');draw();scrollTo(0,0)};$('closeCreate').onclick=()=>{$('profileApp').classList.remove('creating');$('profileError').textContent='';scrollTo(0,0)};$('customTabs').onclick=e=>{const b=e.target.closest('button[data-part]');if(!b)return;part=b.dataset.part;draw()};$('itemOptions').onclick=e=>{const b=e.target.closest('button[data-value]');if(!b)return;const v=b.dataset.value;if(part==='accessory'){if(v==='clear')avatar.accessories=[];else avatar.accessories=avatar.accessories.includes(v)?avatar.accessories.filter(x=>x!==v):[...avatar.accessories,v];}else avatar[part]=v;avatar=norm(avatar);draw()};
$('profilePinToggle').onclick=()=>{const input=$('profilePin');input.type=input.type==='password'?'text':'password'};
function renderPin(){[...$('pinDots').children].forEach((d,i)=>d.textContent=i<pinValue.length?'●':'')}
function syncPinInput(){ $('pinInput').value=pinValue; renderPin(); }
function closePin(){ $('pinDialog').close(); pinValue=''; syncPinInput(); }
function openPin(){pinValue='';$('pinError').textContent='';syncPinInput();$('pinDialog').showModal();setTimeout(()=>$('pinInput').focus(),30)}
async function submitPin(){ if(pinValue.length!==4)return; try{await choose(selectedId,pinValue)}catch(err){$('pinError').textContent=err.message;pinValue='';setTimeout(syncPinInput,100)} }
function onPinKey(k){ if(k==='cancel'){closePin();return;} if(k==='back'){pinValue=pinValue.slice(0,-1);syncPinInput();return;} if(/^[0-9]$/.test(k)&&pinValue.length<4){pinValue+=k;syncPinInput(); if(pinValue.length===4) submitPin();} }
$('pinClose').onclick=closePin;document.querySelector('.drag').onclick=closePin;$('pinPad').onclick=e=>{const b=e.target.closest('button[data-key]');if(!b)return;onPinKey(b.dataset.key)};
$('pinInput').addEventListener('input',e=>{const digits=e.target.value.replace(/\D/g,'').slice(0,4);pinValue=digits;syncPinInput(); if(pinValue.length===4) submitPin()});
$('pinDialog').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closePin();return}if(/^[0-9]$/.test(e.key)){e.preventDefault();onPinKey(e.key);return}if(e.key==='Backspace'){e.preventDefault();onPinKey('back');return}if(e.key==='Enter'){e.preventDefault();submitPin();return}});
$('profilePin').addEventListener('input',e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,4));
$('createProfile').onsubmit=async e=>{e.preventDefault();const name=$('displayName').value.trim(),pin=$('profilePin').value;if(!name)return $('profileError').textContent='프로필명을 입력해 주세요.';if(pin&&!/^\d{4}$/.test(pin))return $('profileError').textContent='PIN은 숫자 4자리로 입력하거나 비워 주세요.';const b=e.submitter;b.disabled=true;$('profileError').textContent='';const payloadAvatar=norm(avatar);try{await rpc('quiz_create_profile_v2',{p_token:ses.token,p_display_name:name,p_pin:pin,p_avatar:payloadAvatar});$('createProfile').reset();avatar={preset:'default',glasses:'default',outfit:'none',accessories:[]};$('profileApp').classList.remove('creating');await load()}catch(err){$('profileError').textContent=err.message}finally{b.disabled=false}};
load();
})();